name: FancySetSpawn
author: patek_cz
version: '1.2'
main: org.patekcz.setSpawn.SetSpawn
api-version: '1.21'
commands:
  setspawn:
    description: Sets the spawn to the player's current location.
  spawn:
    description: Teleports the player to the spawn.
